### ISSUE TITLE
Migration TODO

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/unitpackage#14]
- [x] New zenodo link (see #25)
- [x] Create Pypi repo (https://pypi.org/project/unitpackage/)
- [x] New conda forge repo (see https://github.com/conda-forge/staged-recipes/pull/22836)
- [x] Fix Binder (and all links within the documentation) (see #45 )
- [x] Fix docu (seec #19)
- [x] Rename `database` to `collection` ? (see #17)
- [x] Update Changelog (see #15)

Finalize

- [x] Remove disclaimer from readme (introduced in #16)
- [x] bump to version 0.7.0
